### ISSUE TITLE
suffix = (file.split(repo))[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by HabibRobbani** [AntonMu/TrainYourOwnYOLO#106]
hello my dear

i have an issue after run with colab

  File "/content/drive/My Drive/bayu/yolo/2_Training/Train_YOLO.py", line 185, in <module>
    lines = ChangeToOtherMachine(lines, remote_machine="")
  File "/content/drive/My Drive/bayu/yolo/Utils/Train_Utils.py", line 238, in ChangeToOtherMachine
    suffix = (file.split(repo))[1]
IndexError: list index out of range

**Comment by Varun221** [comment]
For future users, I encountered the same issue and I fixed it by commenting out the line,
lines = ChangeToOtherMachine(lines, remote_machine="")
# LINE 196, Train_YOLO.py
It worked fine without it. Although I am not sure if it is a complete fix, I think it worked for me because I saved the absolute paths in the annotation file.
