### ISSUE TITLE
Issues with Input Shape for larger images!

### ISSUE THREAD

**Issue by dipamgoswami** [AntonMu/TrainYourOwnYOLO#129]
I have images of shape (1000,450,3) which are already annotated. It is recommended to have an input shape which is multiple of 32. I am not sure what should be the input shape in this case. I don't want to split the images since they are already annotated. Any Suggestions?

**Comment by AntonMu** [comment]
I recommend to not change anything in the code at first. Run it with the
default settings and see how it performs. From there, you can start
modifying the code.

**Comment by dipamgoswami** [comment]
Thanks for the Suggestion!

Can you please explain how an input shape of (416,416) will cover the image of shape (1000,450) ?

**Comment by NiklasWilson** [comment]
@dipamgoswami Back when I was playing around with this. my images where all various sizes up to even some 4k images and the annotations where also all random sizes. I didn't have any issues.

**Comment by AntonMu** [comment]
Yep - what @NiklasWilson said is correct. I think the filling color is grey but it's also a parameter that can be changed. Changing the input size has a lot of downstream consequences. For once, you are significantly increasing the size of your kernels (each layer has now more input nodes). Thus, you have to account for this. Also, your weight size increases and you need more memory. That's why it is best to leave it as is to begin with - if you think your performance suffers from it, you can look into changing it. But more often than not, this is not the bottleneck. 

Another way of thinking about it is that you have 416 * 416 * 3 = 519,168 input parameters and `n` (number of classes) output parameters. That is a lot of reduction. Changing this to 3 mio input parameters is probably not going to help that much.
