### ISSUE TITLE
Data Augmentation clarification in darknet53.cfg file

### ISSUE THREAD

**Issue by Franky987** [AntonMu/TrainYourOwnYOLO#150]
I'm looking into the script TrainYourOwnYOLO/2_Training/src/yolo3/darknet53.cfg. There are lines that say 

saturation = 1.5
exposure = 1.5
hue=.1

(...)

jitter=.3
random=1

(...)

I was wondering if these variables are for data augmentation? Or do they have another purpose?

**Comment by AntonMu** [comment]
That is correct - more info for instance [here](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section).

**Comment by Franky987** [comment]
Thanks for the link! 

Closed because question is resolved.

**Comment by robisen1** [comment]
> That is correct - more info for instance [here](https://github.com/AlexeyAB/darknet/wiki/CFG-Parameters-in-the-%5Bnet%5D-section).

are the .cfg files used other than during conversion, i saw yolov3.cfg is used there? If they are used where are they used so that I might learn more and if need be change them to meet the needs of my project which does not work with transfer learning and i am wondering if changing parameters might help train a better model from scratch?
