### ISSUE TITLE
Rotated Bounding box training

### ISSUE THREAD

**Issue by venkataBalavamsi** [AntonMu/TrainYourOwnYOLO#153]
Hello. Thanks for this implementation. Can you please suggest how to train using x_min, y_min,x_max, y_max and theta(angle of rotation) to track oriented bounding boxes while training.

Rectangles don't help always because for rotated objects, they cover extra data which is not needed so I want to implement training on oriented boxes, so the input is x_min, y_min,x_max, y_max and theta instead of x_min, y_min,x_max, y_max.

Thanks for your help in advance.

**Comment by AntonMu** [comment]
Hi @venkataBalavamsi - I don't think the code supports this type of bounding box. I think there are some repos that allow you to rotate bounding boxes. 

What type of objects are you trying to detect?

The issue is that this model has been pre-trained on imagenet with rectangular bounding boxes. If you change the bounding box shape, you can no longer benefit from the pre-trained model and would have to train from scratch. Unless you have a lot of images, you probably won't see good results.
