### ISSUE TITLE
Working on single channel and 16bit images

### ISSUE THREAD

**Issue by diciembre-noche** [AntonMu/TrainYourOwnYOLO#172]
Thanks for your wonderful work! I have followed your instruction and it works perfectly well on RGB images!!

Here are some questions regarding image channel and image type. 
I got two sets of gray scale images:
**1.**	Single channel, 8bit (max pixel value :256)
**2.**	Single channel, 16bit (max pixel value :4096)

It seems that your code is fixed for three channel RGB images. Is there any tips for adjusting your code for my images?

I’ve tried to change some line in order to make it successfully run on my set **1** images. 
(For example:
https://github.com/AntonMu/TrainYourOwnYOLO/blob/9a314d399045aa06ca6992659c7255681be075c6/Utils/Train_Utils.py#L70
https://github.com/AntonMu/TrainYourOwnYOLO/blob/9a314d399045aa06ca6992659c7255681be075c6/Utils/utils.py#L33  )
However, the changes are not enough for testing phase. When I try to run Detector.py, it seems to be much more difficult to adjust the code for single channel. I’m not sure where I should change.

I haven’t tried it on 16bit image. But I found that the code seems to be fixed for 8 bit. (for example: https://github.com/AntonMu/TrainYourOwnYOLO/blob/a5113ff196eebc35f70e92e77e220d34c85bc2a8/2_Training/src/keras_yolo3/yolo.py#L153 )

Do you have any advice for adjusting the code for single channel &16 bit images? Thanks a lot!

**Comment by AntonMu** [comment]
Hi @diciembre-noche ,

Glad you enjoyed using the repo. The easiest solution I can think of is to convert your greyscale images to 8 bit RGB images. The second code snippet seems to do this automatically. 

If you just change the number of channels (like you tried in the first snippet) you need to change the network architecture (overall you'll only have 1/3 of the channels in all layers). But if you do that, you won't be able to use transfer learning anymore because the weights were pre-trained on  RGB images. Also please remember that you can only expect good results if your images are somewhat comparable ImageNet images.

Hope this helps!

**Comment by diciembre-noche** [comment]
I did some trying and found that you are right. Changing image to three channel is the easiest way.
Thank you!
