### ISSUE TITLE
jpg/png and no output for some test images

### ISSUE THREAD

**Issue by emirshekari** [AntonMu/TrainYourOwnYOLO#28]
Hey, thanks for sharing your work. It is very cool ! I enjoyed the output.
A couple of questions though:
1- It seems like the test images has to be in jpg format. isn't it?
2- when for some test images there is no corresponding output in the Test_Image_Detection_Results directory, what does that mean? Yolo didn't find a human face in it?
3- Do you think I can use it to distinguish real vs manipulated faces? (two class classification)
Bests,

**Comment by AntonMu** [comment]
Hey Ellie,

You are welcome! I am glad you enjoyed the code. Here are my answers:

1 - It can be other image formats, too. I have only tested it with *.png and *.jpg though. The reason why it only did *.jpg was that originally [Utils/Get_File_Paths.py ](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/Utils/Get_File_Paths.py) filtered *.jpg files by default. Thanks to your feedback it now updated it so that it also includes *.png and *.jpeg. Thanks!
2 - By default, all processed images will have output images - irrespectively whether the object was found or not. However, in the `Detection_Results.csv` file only images with found objects are listed.
3 - With enough data anything is possible ;) Most of the code should also work for several classes. It has not undergone rigorous testing though. Generally, just follow the same steps as for one class and make different labels when using VoTT. Most of the work should be handled automatically by the code. If you try it out, please share how it goes!!!
