### ISSUE TITLE
Speed!

### ISSUE THREAD

**Issue by philippederouville** [AntonMu/TrainYourOwnYOLO#37]
I've got a question. I launch the script Detector.py from PHP. And it's very long for only one file (jpeg). It's not because of the detection but because of classes ... etc. "model, anchors, and classes loaded in 5.94sec". Is there a way to launch the detection for one file faster ? 
I have a GPU ;)

Thanks so much

**Comment by AntonMu** [comment]
Hi Phillipe - I am not very familiar with PHP but it seems like you could solve this problem by making sure that the model stays in memory - so you don't have to load it again each time. So instead of running the script each time for a single image, leave the script open and wait for a new input.

Something of this form should do the trick (pseudocode):

```
load model
while True:
    new_image = input()
    run_detector on new_image
```

**Comment by philippederouville** [comment]
Thanks! I'll try ;)
