### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Neerucoder** [AntonMu/TrainYourOwnYOLO#47]
![image](https://user-images.githubusercontent.com/22277219/70030270-4abd9a80-15c2-11ea-873f-cb4fad8883be.png)
Getting this error while training after following all instructions on medium article.
Training with six classes instead of one how do i bypass this?

**Comment by AntonMu** [comment]
Hi! Thanks for trying the code. 
1. It looks like you are not loading any training images. Make sure that [`data_train.txt`](https://github.com/AntonMu/TrainYourOwnYOLO/blob/master/Data/Source_Images/Training_Images/vott-csv-export/data_train.txt) is correct. 
2. If you are very familiar with Anaconda it's fine to use it - but as a first step, I recommend to follow the instructions as provided, i.e. using `python3 -m venv env`

**Comment by Neerucoder** [comment]
Thank You, 
There was nothing in my data_train.txt, figured out the issue.

**Comment by Neerucoder** [comment]
![image](https://user-images.githubusercontent.com/22277219/70132589-f8ea4280-169d-11ea-8ebc-56cf1600cb30.png)
Hello after setting the data_train.txt right I got this error even after loading weights
is there any way I can bypass this?

**Comment by AntonMu** [comment]
Hi!

It's because you changed the folder structure. If you want to use a
different structure you have to use command line arguments to specify the
paths of all the necessary data.

To make your life easier, I highly recommend you to follow the instructions
in the Readme 1:1. Once you are familiar with the code, you can start
changing folder names etc.

**Comment by AntonMu** [comment]
Hope you figured it out. Closing the issue now.
