### ISSUE TITLE
Train_YOLO.py stops after printing Epoch 1/51 for tensorflow-gpu

### ISSUE THREAD

**Issue by whatohyou** [AntonMu/TrainYourOwnYOLO#50]
I tried tensorflow-cpu version and it works however gpu version freezes after Epoch 1/51.

Is there a log file somewhere that I can check?

**Comment by TomasTrnkaPLC** [comment]
I have a some problem.
   fetched = self._callable_fn(*array_vals)
  File "C:\ProgramData\Anaconda3\envs\GG2\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_1/convolution}}]]
         [[loss/add_74/_2891]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d_1/convolution}}]]
0 successful operations.
0 derived errors ignored.

**Comment by AntonMu** [comment]
That looks like a problem with your cuda installation. Your Cuda Deep
Neural Network API didn't initialize. Make sure cuda is installed
correctly.

**Comment by TomasTrnkaPLC** [comment]
Can you please share with the version of Cuda and cudnn you use? 
I try a different combinations with anaconda but, nut successfully. Now I try with a cpu but there is a some error

E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] shape_optimizer failed: Invalid argument: Subshape must have computed start >= end since stride is negative, but is 0 and 2 (computed from start 0 and end 9223372036854775807 over shape with rank 2 and stride-1)

**Comment by AntonMu** [comment]
Hi!

I'm using this template from AWS:
https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-Deep-Learning-AMI-Ubuntu-1604/B077GCH38C


There are also some people who trained on their local machines. Check out
the issues page to find their names.

**Comment by TomasTrnkaPLC** [comment]
Ok. One more question. Now I run training via CPU and I have a done
5/5 [==============================] - 168s 34s/step - loss: 55.4228 - val_loss: 55.0710
Unfreeze all layers.
Train on 172 samples, val on 19 samples, with batch size 4.
Epoch 52/102
how many epoch be total?

**Comment by AntonMu** [comment]
It's a total of 102 epochs. But you can also reduce the number of epochs
with the `--epochs` parameter. There is also early stopping. Thus, if you
validation loss doesn't improve, it will stop before all epochs have been
trained.

**Comment by TomasTrnkaPLC** [comment]
Ok. That run. So far I have the first network but, take 7 hours on CPU.  After an epoch 85 from 102, he stops Epoch 00085: early stopping.
But with a GPU is still a problem. I try a different combination but without any success. So far I find a list with a Tensoflow version and cudnn + cuda. Can you please run on your environment this commands?
conda info - to get more info  and
conda info cudnn

thanks

**Comment by AntonMu** [comment]
Hi!

I'm not using conda. My environment is the one from AWS. You can sign up
for an account and test it yourself.

What OS are you using?

**Comment by TomasTrnkaPLC** [comment]
And one more question. Maybe dummy. But If I run train_Yolo 5 times in a row. Every time finish somewhere around 40 epoch what then. Be my model improved or only when all epoch run? Be model improved if I run on him exactly the same set of pictures or he be only improved when I start from scratch - old pictures with new together? I know dummy question but, for me interested.

I use a Windows 10 + Anaconda

**Comment by AntonMu** [comment]
If you run on the same set of pictures you will not see much improvement.
To get better performance you should try and get more data - ie label more
images. In deep learning, an epoch means one full pass through the entire
dataset. Thus, there is no need to run the script many times. It already
goes through the training set many times by default.

**Comment by TomasTrnkaPLC** [comment]
Thanks. So in the case, I need a "super clear answer". I can understand that like.
1.  I have 100Pic. I train that. Then I add next 100 pics to basic set and I again run the script in folder 1 and then in folder 2 training. My new network is created on first 100 + "added" new 100 or be completely generated from start? That mean can be improved or every time is there a new network?
I sorry for a dummy question's but, I think not only for me is type of "questions" unclear.

**Comment by AntonMu** [comment]
Don't run the steps multiple times. First you label all images in step 1
(200 in your case). Then you run the training step in step 2. If you run it
a second time it will "start from 0".

**Comment by TomasTrnkaPLC** [comment]
Again thanks. I gonna try to run that script on Jetson Nano. I let you know results.
Another question. When I train my model I see this.
Epoch 1/51
10/11 [==========================>...] - ETA: 34s - loss: 4670.9468
How I can add also parameter to show me - **acc:** 0.9508 - val_loss: 0.4690 - val_acc: 0.9266

**Comment by AntonMu** [comment]
Hi! The validation loss should be computed at the end of each epoch.

A metric such as accuracy doesn't make sense in the context of object
detection. Usually it's only used for binary classification problems (think
of a yes/no answer) or sometimes it is also used for more general
classification problems with multiple classes.

However, here we are considering several factors such as "is the bounding
box on the object". A common metric for this would be Intersection over
Union (IoU).

**Comment by TomasTrnkaPLC** [comment]
Ok. I have done a solution.
Now my training runs on Windows 10 Tensoflow 2.0-GPU. Problem is with the driver. I need tensorflow2.0 because of I have GTX 1660. What I do is replace to train.py 
`from keras.layers import Input, Lambda
from keras.models import Model`
with
`from tensorflow.keras.layers import Input, Lambda
from tensorflow.keras.models import Model`

then add on bottom of import this.
`import tensorflow as tf
config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.7 # because of memory problem
config.log_device_placement = False  # to log device placement (on which device the operation ran)
sess = tf.compat.v1.Session(config=config)
K.set_session(sess)`
then I run my training without problem. Some warning is there but, training can run.
Some results.
370 Pic set on CPU = 14 hours
370 Pic set on GPU GTX1600 6GB = 2.5Hours

I hope this help someone to run the train on the local machine. The big issue is with convert to tensorflow format but, I hope author help with that.

**Comment by lrscse** [comment]
@AntonMu 
File "C:\Users\Sunil Lourembam\env\lib\site-packages\PIL\Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'C:/Users/Sunil'
how to solve this issue..to overwrite permission

**Comment by AntonMu** [comment]
Glad you solved it! Closing the issue now.
