### ISSUE TITLE
Number of Images for a single Class

### ISSUE THREAD

**Issue by abbasmalik514** [AntonMu/TrainYourOwnYOLO#98]
Can anybody suggest to me how many images are required for a single class of an object to be trained to get accurate results??

**Comment by AntonMu** [comment]
Hi @abbasmalik514 - there is no universal answer to this. It depends on how easy it is to recognize your objects. For instance if you were to just identify black boxes on a white background very little examples are needed. In contrast, if you tried to classify animals and give the detector instances of a lot of different animals which all look different (say elephants, frogs, snakes, etc.) then you would need a lot of training examples. So the answer is: **it depends**. 

It also depends on how similar your objects are to the pre-trained [ImageNet1000](http://www.image-net.org/) training examples. Because of transfer learning, the detector is already skilled at detecting ImageNet1000 type objects even before you start training. 

I would recommend to label as many images as possible and then start training.
